#ifndef CHIP8_COMMON_H
#define CHIP8_COMMON_H

#define MAX_GAME_SIZE (0x1000 - 0x200)

#define TICK_HZ 60
#define TICK_MILLIS (1000/TICK_HZ)

#define CHIP8_DISPLAY_WIDTH 64
#define CHIP8_DISPLAY_HEIGHT 32

#define CHIP8_DISPLAY_WIDTH_BYTES  (CHIP8_DISPLAY_WIDTH / 8)

#define DISPLAY_BUFFER_SIZE (CHIP8_DISPLAY_HEIGHT * CHIP8_DISPLAY_WIDTH_BYTES)

#define SPRITES_START_ADDRESS 0
#define SPRITE_SIZE_IN_BYTES 5
#define SPRITES_COUNT 16

// MEMORY
#define MEMORY_SIZE 4096

// SDL2
#define WINDOW_NAME "Chip8 Emulator"
#define SCALE 10
#define WINDOW_WIDTH (CHIP8_DISPLAY_WIDTH * SCALE)
#define WINDOW_HEIGHT (CHIP8_DISPLAY_HEIGHT * SCALE)

#endif //CHIP8_COMMON_H
